---
title: "Question4, (h)"
output:output:
  html_document:
    df_print: paged
  html_notebook: 
    code_folding: hide
---


# g.1
```{r echo=FALSE} 

########### Training data (rankings only, no dates):
con = url("http://www.tau.ac.il/~saharon/StatsLearn2018/train_ratings_all.dat")
X.tr = read.table (con)
con = url("http://www.tau.ac.il/~saharon/StatsLearn2018/train_y_rating.dat")
y.tr = read.table (con)

con = url("http://www.tau.ac.il/~saharon/StatsLearn2018/movie_titles.txt")
titles = read.table(con,sep=",")
names(X.tr) = substr(as.character(titles[,2]),1,15)
movies = substr(as.character(titles[,2]),1,15)

### Keep 50 first rows ####
X.tr = X.tr[1:50,]
y.tr = y.tr[1:50,]
trtr = data.frame (X = X.tr,y=y.tr)

```
## Lasso
```{r echo=FALSE} 
library(lasso2)
norm.vals = seq (10e-5, 0.2,by=0.01)


mods = l1ce(y~.+1,data=trtr, bound=norm.vals) # l1ce outputs a list of models
preds = sapply (mods, predict, newdata=trtr) # example of lapply!
resids = apply (preds, 2, "-", trtr$y)
RSSs = apply(resids^2, 2, sum)
lambdas = as.numeric(sapply (mods, "[",5))

plot (lambdas, sqrt(RSSs), main=paste("Lasso - RSS VS lamdba"),ylab="RSS",xlab="lambda",log="x")
plot (norm.vals, as.numeric(RSSs), main=paste("Lasso - RSS VS s"), ylab="RSS",xlab="s")


```

## Ridge
```{r echo=FALSE} 
###### Ridge
library(MASS)
lambda.vals = exp(seq(-15,10,by=0.1))


mods = lm.ridge(y~.,data=trtr, lambda=lambda.vals)
preds = as.matrix(X.tr) %*% t(coef(mods)[,-1]) +  rep(1,50) %o% coef(mods)[,1]
resids = matrix (data=y.tr, nrow=dim(preds)[1], ncol=dim(preds)[2], byrow=F)-preds
RSSs = apply (resids^2, 2, sum)
plot (mods$lambda, RSSs, main=paste("Ridge- RSS VS lamdba",sep=""),ylab="RSS",xlab="lambda",log="x")
plot (apply(mods$coef^2, 2, sum), RSSs, main=paste("Ridge - RSS VS s",sep=""), ylab="RSS",xlab="s",xlim=c(0,1.5))


```


# g.2

## Lasso
```{r} 
norm.vals = 0.15
mods = l1ce(y~.+1,data=trtr, bound=norm.vals) # l1ce outputs a list of models
l1 = sum(abs(mods$coef[c(2:100)]))
l2 = sum((mods$coef[c(2:100)])**2)

cat("For Lasso:\nL1=",l1,"\nL2=",l2)

```


## Ridge
```{r} 
library(MASS)
lambda.vals = exp(-15)

mods = lm.ridge(y~.,data=trtr, lambda=lambda.vals)
l1 = sum(abs(mods$coef))
l2 = sum((mods$coef)**2)
cat("For Ridge:\nL1=",l1,"\nL2=",l2)
```

