---
title: "4. Absolute loss kernel regression"
output:output:
  html_document:
    df_print: paged
  html_notebook: 
    code_folding: hide
---


# Absolute loss kernel regression
```{r} 

########### Training data (rankings only, no dates):
con = url("http://www.tau.ac.il/~saharon/StatsLearn2018/train_ratings_all.dat")
X.tr = read.table (con)
con = url("http://www.tau.ac.il/~saharon/StatsLearn2018/train_y_rating.dat")
y.tr = read.table (con)

con = url("http://www.tau.ac.il/~saharon/StatsLearn2018/movie_titles.txt")
titles = read.table(con,sep=",")
names(X.tr) = substr(as.character(titles[,2]),1,15)
movies = substr(as.character(titles[,2]),1,15)

### Keep 50 first rows ####
X.tr = X.tr[1:100,]
y.tr = y.tr[1:100,]
trtr = data.frame (X = X.tr,y=y.tr)

```

## 1) 
```{r} 
library ("e1071")
err.rbf = NULL
gamma = 0.0001
cost.val = exp(seq(-5,10,by=0.1))
for (c in cost.val){
    mod.svm = svm(y~., data=trtr, type="eps-regression", gamma=gamma,  epsilon=0, cost=c)
    pr.svm=predict(mod.svm,newdata=trtr)
    err.rbf = c(err.rbf, mean (abs(pr.svm-trtr$y)))

}
plot (cost.val, err.rbf, main="Support vector regression- Gamma=0.0001", xlab="Cost", ylab="mean absolute loss",
      type="l",log="x")



```

```{r}
err.rbf = err.tr.rbf = NULL
gamma = 5
cost.val = exp(seq(-5,10,by=0.1))
for (c in cost.val){
    mod.svm = svm(y~., data=trtr, type="eps-regression", gamma=gamma,  epsilon=0, cost=c)
    pr.svm=predict(mod.svm,newdata=trtr)
    err.rbf = c(err.rbf, mean (abs(pr.svm-trtr$y)))
}
plot (cost.val, err.rbf, main="Support vector regression- Gamma=5", xlab="Cost", ylab="mean absolute loss",
      type="l",log="x")


```

## 3)
### Gamma=0.0001
```{r}
trtr[101,] = rep(5, 100)
new_obs = rep(5, 99)
err.rbf = err.tr.rbf = NULL
gamma = 0.0001
c = exp(15)
mod.svm = svm(y~., data=trtr[1:100,], type="eps-regression", gamma=gamma,  epsilon=0, cost=c)
pr.svm=predict(mod.svm,newdata=trtr[101,])
cat("The prediction with Gamma = 0.0001 is:", pr.svm)
```


### Gamma=5
```{r} 
trtr[101,] = rep(5, 100)
new_obs = rep(5, 99)
err.rbf = err.tr.rbf = NULL
gamma = 5
c = exp(15)
mod.svm = svm(y~., data=trtr[1:100,], type="eps-regression", gamma=gamma,  epsilon=0, cost=c)
pr.svm=predict(mod.svm,newdata=trtr[101,])
cat("The prediction with Gamma = 0.0001 is:", pr.svm)
```
